### ISSUE TITLE
RTO cash amount is considered in HK.com cash collection

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#434]
Dwarka sec 10

Date: 04 July

RTO Cash collection : 349 (delivery by SM) is subtracting from HK.com Cash collection

Without RTO cash collection total cash amount should be (1268 -100) ie 1160 but it is displaying as 819

![image](https://user-images.githubusercontent.com/14803102/60668227-19ad3280-9e89-11e9-9a35-9e1d3958f8ad.png)

![image](https://user-images.githubusercontent.com/14803102/60668244-229e0400-9e89-11e9-8458-ad07f9e8aae6.png)

**Comment by sharangsamonkar** [comment]
**dwarka sec 1- july 4 hk.com orders**
**cash = 599** (HKD-52243-17935809) **+ 549** (HKD-04302-17935811) **+ 100** (HKD-99170-17935813) **+ 120** (HKD-46262-17935817) **- 549** (HKD-99170-17935813) **= 819**

The amount of HKD-10468-17935815 is not added because it is not yet delivered.
Only the delivered orders collection is added

**Comment by rohan-morje** [comment]
Rpu -120. Need to subtract

**Comment by sharangsamonkar** [comment]
HKD-99170-17935813 is the rpu order which is 100 cash + 449 paytm = 549.
This is subtracted because regardless of the payment mode the amount is subtracted from the cash collection.

**Comment by rohan-morje** [comment]
Ok
